name: React to external commit

on:
  workflow_dispatch:
    inputs:
        repository:
            description: 'Repository name in the form of owner/repo'
            required: true
        commit:
            description: 'Commit SHA'
            required: true
        actor:
            description: 'Actor'
            required: true
        message:
            description: 'Commit message'
            required: false

jobs:
    react:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                echo "Repo: ${{ github.event.inputs.repository }}"
                echo "Actor: ${{ github.event.inputs.actor }}"
                echo "Commit SHA: ${{ github.event.inputs.commit }}"
                echo "Message: ${{ github.event.inputs.message }}"
        