name: React to external commit

on:
  workflow_dispatch:
    inputs:
        commit:
            description: 'Commit SHA'
            required: true
        actor:
            description: 'Actor'
            required: true
        message:
            description: 'Commit message'
            required: true

jobs:
    react:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo "${{ toJSON(github.event) }}"
        