name: React to external commit

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
    react:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo ${{ github.event }}
        